# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: webing3
  labels:
    app: webing3
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: webing3
  type: NodePort