# Ingress resource for the application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webing3
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: webing3.local
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webing3
            port:
              number: 80
